# redis-cli -p 26379

port 26379
dir /tmp

# Enable IP-based tracking (Turn off hostname fallbacks)
sentinel resolve-hostnames no
sentinel announce-hostnames no

sentinel monitor mymaster 172.99.0.10 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
